small_tasks/config/routes.rb
Rails.application.routes.draw do
#   get 'blog_functions/index'

#   get 'blog_functions/show'

#   get 'blog_functions/edit'

#   get 'blog_functions/update'

#   get 'blog_functions/destroy'

 # get 'contacts/new'

  #get 'contacts/create'
   resources :contacts
#   resources :blog_functions
   resources :blog_functions do
    collection do
      post :confirm
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

small_tasks/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

small_tasks/app/models/blog_function.rb
class BlogFunction < ApplicationRecord
    validates :content, presence: true, length: { in: 1..140 }
end

small_tasks/app/models/contact.rb
class Contact < ApplicationRecord
    #validates :content, length: { in: 1..140, too_short: "%{count} characters is the maximum allowed" }  
    validates :content, presence: true, length: { in: 1..140 }
end

small_tasks/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

small_tasks/app/controllers/blog_functions_controller.rb
class BlogFunctionsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blog_functions = BlogFunction.all
  end

  def new
    @blog_function = BlogFunction.new
  end 
  
  
  def create
  @blog_function = BlogFunction.new(function_params)
    if @blog_function.save
      redirect_to blog_functions_path, notice: "You have created new blog function!"
    else
      render 'new'
    end 
  end
  
  def show
    @blog_function = BlogFunction.find(params[:id])
  end

  def edit
    @blog_function = BlogFunction.find(params[:id])
  end

  def update
    @blog_function = BlogFunction.find(params[:id])
    if @blog_function.update(function_params)
      redirect_to blog_functions_path, notice: "You have edited this blog function！"
    else
      render 'edit'
    end
  end

  def destroy
   @blog_function.destroy
    redirect_to blog_functions_path, notice: "You have deleted this blog function!" 
  end
  
  private 
  def function_params
  params.require(:blog_function).permit(:name, :email, :content)
  end
  def set_blog
      @blog_function = BlogFunction.find(params[:id])
  end 
end

small_tasks/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(name: params[:contact][:name], email: params[:contact][:email], content: params[:contact][:content])
   if @contact.save
    redirect_to new_contact_path
  else
    render 'new'
  end
  end
  
  
  
  # private
  # def blog_params
  #   params.require(:contact).permit(:name, :email, :content)
  # end
end

small_tasks/app/helpers/application_helper.rb
module ApplicationHelper
end

small_tasks/app/helpers/blog_functions_helper.rb
module BlogFunctionsHelper
end

small_tasks/app/helpers/contacts_helper.rb
module ContactsHelper
end

small_tasks/app/views/blog_functions/edit.html.erb
<h2>Update this blog function</h2>

 <%= form_with(model: @blog_function, local: true) do |form| %>
  <% if @blog_function.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog_function.errors.count %>errors occurred.</h2>
      <ul>

      <% @blog_function.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="function_name">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="function_name">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="function_name">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

small_tasks/app/views/blog_functions/index.html.erb
<h1>List of blog function</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>Name</th>
    <th>E-mail</th>
    <th>Content</th>
  </tr>

<% @blog_functions.each do |blog_function| %>
  <tr>
    <td><%= blog_function.name %></td>
    <td><%= blog_function.email %></td>
    <td><%= blog_function.content %></td>
    <td><%= link_to 'Check the Blog function details', blog_function_path(blog_function.id) %></td>
    <td><%= link_to 'Edit this Blog function', edit_blog_function_path(blog_function.id) %></td>
    <td><%= link_to "Delete this blog function", blog_function_path(blog_function.id), method: :delete ,data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to 'Post a new blog function', new_blog_function_path %>

small_tasks/app/views/blog_functions/new.html.erb
<h2>Create a new blog function</h2>

 <%= form_with(model: @blog_function, local: true) do |form| %>
  <% if @blog_function.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog_function.errors.count %>errors occurred.</h2>
      <ul>

      <% @blog_function.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="function_name">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="function_name">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="function_name">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

small_tasks/app/views/blog_functions/show.html.erb
<h1>Blog Function Detail Screen </h1>

    <p>Name:    <%= @blog_function.name %></p>
    <p>Email:   <%= @blog_function.email %></p>
    <p>Content: <%= @blog_function.content %></p>
<br>
<%= link_to 'Return to Blog Function List', blog_functions_path %>

small_tasks/app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

small_tasks/app/views/contacts/new.html.erb
<%= form_with(model: @contact, local: true ) do |form| %>
<% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@contact.errors.count, "error") %>
      </h2>
      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



<div class="contact_name">
    <%= form.label :name %>
    <%= form.text_field :name %>
</div>
    
<div class="contact_name"> 
    <%= form.label :email %>
    <%= form.text_field :email %>
</div>

<div class="contact_name"> 
    <%= form.label :content %>
    <%= form.text_field :content %>
</div>

<%= form.submit %>

<% end %>

small_tasks/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmallTasks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>