sample/config/routes.rb
Rails.application.routes.draw do
  #get 'stocks/index'
 # get '/stocks', to: 'stocks#index'
  #get '/blogs', to: 'blogs#index'
  
  resources :blogs do
    collection do
      post :confirm
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sample/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sample/app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, presence: true
end

sample/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

sample/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
 
 
 before_action :set_blog, only: [:show, :edit, :update, :destroy]
 
  def index
    @blogs=Blog.all
   #binding.pry
   #raise
  end
  
  
  #define new page for entering new data 
  def new
  if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
  end 
  end
  
  
  #define update method
  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "You have edited this blog！"
    else
      render 'edit'
    end
  end
#after entering the data , it will insert it into the controller table and create an action on the button for saving  
 
 
 def create
  #we use it in order to display the input data after saving it 
   # Blog.create(title: params[:blog][:title], content: params[:blog][:content])
   
   #we are using the concise way 
   # Blog.create(blog_params)
    
#for redirecting the page to the new page after registrating the data 
#redirect_to "/blogs/new"
   #redirect_to new_blog_url
  # redirect_to new_blog_path
  
  @blog = Blog.new(blog_params)
    if @blog.save
      # Switch to the list screen and display a message saying "You have created new blog!"
      redirect_to blogs_path, notice: "You have created new blog!"
    else
      # Redraw the input form.Back to the new.html.erb page 
      render 'new'
    end end
  
  
#to use the show action, we need to get the record from params method and find method by using the id as follows
def show 
  #params[:id]
  @blog = Blog.find(params[:id])
end


#to use the edit action, we need to get the record from params method and find method by using the id as follows
 def edit
   @blog = Blog.find(params[:id]) end


#define a destroy action  by getting the records by using the params and find method using the id and after redirect the page to the index action 
 def destroy
   @blog.destroy
    redirect_to blogs_path, notice: "You have deleted the blog!" end
    
 def confirm
    @blog = Blog.new(blog_params)
    render :new if @blog.invalid?
 end

#in order to use strong parameter for security we are going to use this method  which is a private method
private
  def blog_params
    params.require(:blog).permit(:title, :content)
  end

# method to get the value by setting id as key
    def set_blog
      @blog = Blog.find(params[:id])
    end  
end

sample/app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
  end
end

sample/app/helpers/application_helper.rb
module ApplicationHelper
end

sample/app/helpers/blogs_helper.rb
module BlogsHelper
    def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end end
end

sample/app/helpers/stocks_helper.rb
module StocksHelper
end

sample/app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>errors occurred.</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "Return to List of blogs screen", blogs_path %>

sample/app/views/blogs/confirm.html.erb
<h3>Send it with the following contents.</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <p>Title:<%= @blog.title %></p>
  <p>Body:<%= @blog.content %></p>
  <%= form.submit  "submit" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit "Back", name: 'back' %>
<% end %>

sample/app/views/blogs/edit.html.erb
<h2>Update this blog</h2>

  <%= render 'form' %>

sample/app/views/blogs/index.html.erb
<h1>List of blogs</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>Title</th>
    <th>Content</th></th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    
    <td><%= link_to 'Check the details', blog_path(blog.id) %></td>
    <td><%= link_to "Edit this blog", edit_blog_path(blog.id) %></td>
    <td><%= link_to "Delete this blog", blog_path(blog.id), method: :delete ,data: { confirm: 'Are you sure?' } %></td>
    
  </tr>
<% end %>
</table>

<br>

<%= link_to 'Post a new blog', new_blog_path %>

sample/app/views/blogs/new.html.erb
<h2>Create a new blog</h2>

  <%= render 'form' %>

sample/app/views/blogs/show.html.erb
<h1>Blog Detail Screen </h1>
<p>Title: <%= @blog.title %></p>
<p>Contents: <%= @blog.content %></p>

sample/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

sample/app/views/stocks/index.html.erb
<h1>Stocks#index</h1>
<p>Find me in app/views/stocks/index.html.erb</p>